package juloo.keyboard2;

import android.app.Activity;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

public class TypingMasterActivity extends Activity {

    private TextView tvParagraph;
    private EditText etTypingArea;
    private Button btnNext;

    private String[] paragraphs = {
        "The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog. The quick brown fox jumps over the lazy dog.",
        "Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work. Technology has revolutionized the way we live and work.",
        "Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities. Learning to code opens up a world of possibilities.",
        "Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty. Nature offers a profound sense of tranquility and beauty.",
        "Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge. Reading books is a wonderful way to expand your knowledge.",
        "Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships. Effective communication is key to building strong relationships.",
        "Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle. Exercise is vital for maintaining a healthy lifestyle.",
        "Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures. Traveling allows us to experience new cultures.",
        "Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries. Music has a universal language that transcends boundaries.",
        "A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges. A positive mindset can transform your approach to challenges."
    };

    private int currentParagraphIndex = 0;
    private long startTime;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_typing_master);

        tvParagraph = findViewById(R.id.tv_paragraph);
        etTypingArea = findViewById(R.id.et_typing_area);
        btnNext = findViewById(R.id.btn_next);

        loadParagraph();

        etTypingArea.addTextChangedListener(new TextWatcher() {
            @Override
            public void beforeTextChanged(CharSequence s, int start, int count, int after) {}

            @Override
            public void onTextChanged(CharSequence s, int start, int before, int count) {
                if (etTypingArea.getText().toString().length() == 1) {
                    startTime = System.currentTimeMillis();
                }
            }

            @Override
            public void afterTextChanged(Editable s) {
                if (s.toString().equals(paragraphs[currentParagraphIndex])) {
                    long endTime = System.currentTimeMillis();
                    long timeTaken = endTime - startTime;
                    int words = s.toString().split("\\s+").length;
                    double wpm = (words / (timeTaken / 60000.0));
                    android.widget.Toast.makeText(TypingMasterActivity.this, "Completed! Speed: " + Math.round(wpm) + " WPM", android.widget.Toast.LENGTH_LONG).show();
                    btnNext.setEnabled(true);
                }
            }
        });

        btnNext.setOnClickListener(v -> {
            currentParagraphIndex = (currentParagraphIndex + 1) % paragraphs.length;
            loadParagraph();
            etTypingArea.setText("");
            btnNext.setEnabled(false);
        });
    }

    private void loadParagraph() {
        tvParagraph.setText(paragraphs[currentParagraphIndex]);
    }
}
// Added file to manifest
// Updated Activity logic correctly
